### ISSUE TITLE
Add a cf-enhancements.less file

### ISSUE THREAD

**Issue by himedlooff** [cfpb/generator-cf#11]
In cfgov-refresh we have a file named `cf-enhancements.less` <https://github.com/cfpb/cfgov-refresh/blob/gh-pages/static/css/cf-enhancements.less>. Any time we need to style something that seems like it would be good to add/change/update in a Capital Framework we add it to this file. Doing this makes it easier to remind us to contribute back. I wonder if adding this file to the generator would help people do the same?

**Comment by jimmynotjim** [comment]
I agree, each project that uses CF should include this file to make contributing back to CF simpler. Working on a PR now.
