### ISSUE TITLE
Add an .npmrc file

### ISSUE THREAD

**Issue by ascott1** [cfpb/generator-cf#113]
Idea from <https://blog.heroku.com/archives/2015/11/10/node-habits-2016#2-use-a-smart-npmrc>

We could add a "smart" `.npmrc` file that will automatically enforce `--save-exact`.

**Comment by Scotchester** [comment]
Seems like a good idea :+1:

Wouldn't mind exploring shrinkwrapping further, too.

**Comment by JeffreyMFarley** [comment]
FYI: I followed the instructions [here](https://cfpb.github.io/capital-framework/getting-started/) and I had the script fail after the yo "interview"

```shell
✔ Done in _cache
/Users/farleyj/homebrew/lib/node_modules/generator-cf/node_modules/yeoman-generator/lib/actions/actions.js:191
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e.code + ').');
    ^

Error: Unable to read "/Users/farleyj/homebrew/lib/node_modules/generator-cf/app/templates/.npmrc" file (Error code: ENOENT).
    at read (/Users/farleyj/homebrew/lib/node_modules/generator-cf/node_modules/y
```

I fixed it by manually downloading the `.npmrc` file from this repository and placing it in the appropriate spot.  

Thought you should know that the npm package does not have quite everything

**Comment by Scotchester** [comment]
@JeffreyMFarley Thanks for the note, Jeff!

I bet we're getting bit by this:

> **NOTE:** Because local (per-project or per-user) `.npmrc` files can contain sensitive credentials, they must be readable and writable _only_ by your user account (i.e. must have a mode of `0600`), otherwise _they will be ignored by npm!_
>
> –`npmrc` docs, https://docs.npmjs.com/files/npmrc

/cc @contolini
