### ISSUE TITLE
Why aren't all CF component version numbers being written to bower.json?

### ISSUE THREAD

**Issue by contolini** [cfpb/generator-cf#12]
See #5.

**Comment by Scotchester** [comment]
Update: cf-buttons now has a version number, cf-icons still does not.

**Comment by jimmynotjim** [comment]
Running this on a test directory today all components have version numbers. Can someone else confirm so we can close this out?

**Comment by anselmbradford** [comment]
Can we close this? Are we still using Bower at all?

**Comment by Scotchester** [comment]
No we are not.
