### ISSUE TITLE
Update `lint:gulp` to `lint:build`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#126]
[This line](https://github.com/cfpb/generator-cf/blob/master/app/templates/gulp/gulp/config.js#L31) should be `build` instead of `gulp` and should include `'config/**/*.js'` in the file list.

**Comment by jimmynotjim** [comment]
Looks like half of this was done but the `config/**/*.js` wasn't.

**Comment by anselmbradford** [comment]
Yeah I noticed that too.
