### ISSUE TITLE
Default width differs from cfgov-refresh

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#130]
## Current behavior

- https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/cf-theme-overrides.less#L159 is 30px wider than https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/cf-theme-overrides.less#L147

## Expected behavior

- Seems like the default should follow the width used in cfgov-refresh so that projects within CFPB that use the generator as a starting point have the correct width for the header alignment with content.

**Comment by Scotchester** [comment]
Nay, cfgov-refresh is the incorrect one. See: https://[GHE]/CFGOV/platform/issues/244
