### ISSUE TITLE
gulp-less error on webfont rules in main.less sample styles

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/generator-cf#137]
The `gulp-less` task throws an error when the Yeoman generator first tries to build the project (and on any subsequent `gulp build`, too).

## Current behavior

At the end of the `yo cf` process, the build script (gulp, in this case) builds the project. Looks like there are some undefined LESS mixins in the sample styles in `main.less` that are causing an error in `gulp-less`.

## Expected behavior

All the gulp tasks should run without errors. Looks like the webfont rules in the sample styles just need to be prefixed with `u-` to work right.

## Steps to replicate behavior

1. Update the Yeoman Capital Framework generator to the latest version
2. `yo cf`
3. Enter anything for all the setup questions
4. Select all CF components
5. Select gulp as the build tool
6. Wait for the generator to start running `gulp build`
7. Note the error: `.webfont-medium is undefined in file /[path]/src/static/css/main.less line no. 41`
8. If you comment out line 41, a similar error will happen for the `.webfont-regular` mixin on lines 58 and 121 of `main.less`, too.

## Screenshots

![terminal](https://cloud.githubusercontent.com/assets/1862695/25718660/e887c5d6-30d4-11e7-8bd0-c399963cc63e.png)

**Comment by jimmynotjim** [comment]
@niqjohnson thanks for finding this, I messed up in the CFv4 upgrade and missed a few things. I'll get this fixed.

**Comment by anselmbradford** [comment]
This may be fixed?

**Comment by jimmynotjim** [comment]
Yep, we've completely removed the web font mixins from CF.

**Comment by Scotchester** [comment]
The original issue was closed by @anselmbradford in https://github.com/cfpb/generator-cf/commit/0d6fb5fa4129fafa35897bdd341523db38a37663#diff-58b52ce1dd4b9183b07d419539316086

@jimmynotjim We'll _also_ need to remove the webfont mixins from the sample `main.less` file now that we're deprecating them.

**Comment by jimmynotjim** [comment]
Addressed in #149
