### ISSUE TITLE
Replace jshint with eslint

### ISSUE THREAD

**Issue by contolini** [cfpb/generator-cf#21]

**Comment by himedlooff** [comment]
Why? What's the difference?

**Comment by contolini** [comment]
It's AST-based and pluggable so you can check against rules that are incredibly specific. Things like: http://eslint.org/docs/rules/space-in-parens.html

**Comment by himedlooff** [comment]
I dig it!


![selfie-1](http://i.imgur.com/j7VtfHO.gif)

**Comment by jimmynotjim** [comment]
#54 Fixes this. Closing.
