### ISSUE TITLE
Can we remove the white option in .jshintrc?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/generator-cf#24]
The `white` option forces a space after `function` and before `()`. This is not an idiomatic standard and I think it should be removed.

**Comment by Scotchester** [comment]
I think this issue is obsolete following our implementation of ESLint.

**Comment by anselmbradford** [comment]
It's a setting available in ESLint, but yup, disallowed in the eslint file that was migrated into standard https://github.com/cfpb/front-end/blob/master/.eslintrc#L478
