### ISSUE TITLE
Improve Bower failure handling

### ISSUE THREAD

**Issue by Scotchester** [cfpb/generator-cf#30]
During initial generation, if the [Bower install step](https://github.com/cfpb/generator-cf/blob/master/app/index.js#L182) fails (say, for example, you're not connected to the VPN and can't SSH to GitHub from inside the building... :expressionless:), you have no way to recover other than blowing it away and starting fresh.

It'd be better if the dependencies could be added to the `bower.json` file first, and then they'll be installed with the [`postinstall` script](https://github.com/cfpb/generator-cf/blob/master/app/templates/_package.json#L37) when running `npm install` [here](https://github.com/cfpb/generator-cf/blob/master/app/index.js#L181).

(Relatedly, isn't the `bower install` piece of that `postinstall` script redundant, since `compile-cf` runs the `bower:cf` Grunt task?)

**Comment by contolini** [comment]
Cool, some notes from our in-person discussion:
- Write out config options http://yeoman.io/authoring/storage.html
- Write to bower.json and let the components get installed in the post install
- Improve error handling, don't fail silently if bower fails

**Comment by jimmynotjim** [comment]
@Scotchester `compile-cf` doesn't install the dependencies, it's set to `false`. 

@contolini what is your bullet on writing the config options related to? 

I've got a somewhat working update at #52 but I'm not sure what's the best way to get the latest version, any ideas? My initial thought was to grab them when we grab the list of components during the init. Is there something simpler I'm missing?

**Comment by Scotchester** [comment]
@jimmynotjim Oh yeah, good point.

Yeah, getting the latest when grabbing the list makes sense to me.

**Comment by jimmynotjim** [comment]
#52 is now working and with `bower install` is run as an NPM post install script it should error out leaving you with the option to re-run `bower install` on your own.

**Comment by jimmynotjim** [comment]
#52 fixes this issue, closing it out.
