### ISSUE TITLE
Question should /vendor folder be removed from .gitignore ?

### ISSUE THREAD

**Issue by djdrisco** [cfpb/generator-cf#38]
Should /vendor folder be included ? It is currently in the .gitignore file (project: generator-cf)?
The reason I ask is when I go thru the steps in : http://cfpb.github.io/capital-framework/getting-started/
I run thru the steps including : grunt compile-cf, then make a small change,
and then run: grunt
I get this error: 
Running "less:main" (less) task
 FileError: '../../vendor/normalize-css/normalize.css' wasn't found in src/static/css/main.less on line 9, column 1:
 8 // Import Normalize, a Capital Framework dependency and an all-around best practice.
 9 @import (less) "../../vendor/normalize-css/normalize.css";
 10 @import (less) "../../vendor/normalize-legacy-addon/normalize-legacy-addon.css";

**Comment by himedlooff** [comment]
Hmmm, are you getting anything installed into the vendor folder? We have been having issues lately where the bower install step has been failing which leaves the dependencies in bower.json empty. This also means that the vendor folder never gets installed.

**Comment by jimmynotjim** [comment]
Ignoring the directory in git doesn't remove it from the project, it just removes it from being tracked by git and committed to the repo. This keeps the repo size smaller while allowing everyone to build from the same assets.

Try running `bower install && grunt compile-cf` to rebuild the assets and src directory.

**Comment by djdrisco** [comment]
I reran the steps from a new folder using the getting started steps above and everything went smoothly, so I'm all set.

**Comment by jimmynotjim** [comment]
Awesome
