### ISSUE TITLE
Release tags are inconsistent

### ISSUE THREAD

**Issue by Scotchester** [cfpb/generator-cf#40]
https://github.com/cfpb/generator-cf/releases

**Comment by jimmynotjim** [comment]
How do you mean?

Side note. It's hard to tell what's changed without release descriptions. We should copy the changes listed in the changelog to these (which is missing half the releases itself).

**Comment by Scotchester** [comment]
Some have the `v` prefix, some don't.

I am not a stickler for putting the notes into the GitHub release description, **if** the changelog is kept up to date. (Which needs to happen, regardless.)

**Comment by jimmynotjim** [comment]
Ah, I was looking at the numbering an totally bypassed the prefix.

**Comment by jimmynotjim** [comment]
Looking at other projects, it seems we prefer tags without the `v` prefix. If that's the case I can update these when I tag the fixes from today.

**Comment by Scotchester** [comment]
I think we do, yes. Sounds like a plan :+1:

**Comment by jimmynotjim** [comment]
Figured I had some time before we finish the other two PRs so I went ahead and replaced these. Closing.

**Comment by Scotchester** [comment]
Thanks!
