### ISSUE TITLE
package.json output issues

### ISSUE THREAD

**Issue by Scotchester** [cfpb/generator-cf#41]
- Weird spacing seen here:

  ![screen shot 2015-03-17 at 11 55 37](https://cloud.githubusercontent.com/assets/1044670/6691394/b16ab7aa-cc9c-11e4-96be-437809d40840.png)

  (spaces before terminating comma of `author.email`, extra indentation before `author.url`)
- `repository` field is missing.

**Comment by jimmynotjim** [comment]
This is due to a condition in the [template](https://github.com/cfpb/generator-cf/blob/master/app/templates/_package.json#L8-L11).

**Comment by Scotchester** [comment]
Would it hurt the readability too much to adjust the template so the extra spaces won't appear?

**Comment by jimmynotjim** [comment]
I don't think so. The readability of resulting file is more important than the template.
