### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/generator-cf#43]
While updating cfgov-refresh I found the existing `.gitignore` is far more robust. Should we include some of these file types?

```
# Compiled source #
###################
*.com
*.class
*.dll
*.exe
*.o
*.so
_site/

# Packages #
############
# it's better to unpack these files and commit the raw source
# git has its own built in compression methods
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Logs and databases #
######################
*.log
*.sql
*.sqlite

# Topdoc stuff #
##################
docs/*/pdfreactor-fonts.html

# Testing stuff #
##################
_tests/browser_testing/features/environment.cfg
```

**Comment by Scotchester** [comment]
The "Topdoc stuff" and "Testing stuff" sections are probably too project specific, but the others should go in. It should also be kept in sync with [cfpb/open-source-project-template](https://github.com/cfpb/open-source-project-template)

**Comment by jimmynotjim** [comment]
Thanks, created a [PR over there](https://github.com/cfpb/open-source-project-template/pull/12)
