### ISSUE TITLE
Why isn't proposed brand color in cf-enhancements

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#59]
`@dark-redorange` is listed as an `// Unofficial or proposed colors` in https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/brand-palette.less#L30

Shouldn't it be in https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/cf-enhancements.less instead? 

Also, what's the migration path to make it an official color?

**Comment by Scotchester** [comment]
Because that line of code goes back almost two years to well before cf-enhancements existed :)

I don't think it needs to be made an official color. It only really has one use: active state on destructive actions.

**Comment by anselmbradford** [comment]
> Because that line of code goes back almost two years to well before cf-enhancements existed :)
>
> I don't think it needs to be made an official color. It only really has one use: active state on destructive actions.

Kind of sounds like it already is an official color if it's in use for two years? What makes a color "official" vs not?

**Comment by Scotchester** [comment]
>What makes a color "official" vs not?

Whether or not it appears here: http://cfpb.github.io/design-manual/identity/color-principles.html

**Comment by anselmbradford** [comment]
Ahh, would it make sense to have https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/brand-palette.less#L6 line to that?

**Comment by Scotchester** [comment]
Yeah, it would. Good call! Should've revisited that when the Design Manual was released.

**Comment by anselmbradford** [comment]
What's the canonical source of `brand-palette.less`? Is it this repo?

**Comment by Scotchester** [comment]
I believe so; see also: `cf-theme-overrides.less`.
