### ISSUE TITLE
Consider renaming pkg variable in Gruntfile

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#70]
The `pkg` variable in the Gruntfile really makes it seem like it's referencing `package.json`, when in fact it's referencing [`bower.json`](https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L18).
Even the code comment thinks it's [`package.json`](https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L16). Can this have either a bower-specific name or a more general name like `metadata` or equivalent?

**Comment by jimmynotjim** [comment]
We could reference the `package.json` instead of `bower.json` like most generators do. Generated projects have complete manifests for both managers so there's no reason not to.

**Comment by anselmbradford** [comment]
This now references `package.json` https://github.com/cfpb/generator-cf/blob/master/app/templates/grunt/_Gruntfile.js#L24
