### ISSUE TITLE
bower task should have `verbose` set to `false`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#75]
Bower packages are manually installed in `src/vendor` in https://github.com/cfpb/generator-cf/blob/master/app/templates/bowerrc

Bower Grunt task targets the [same directory](https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L36) (which it needs to because `install: false` is set), so what ends up happening is all the bower packages are copied over themselves in the same directory.

The `copy: false` flag should be set on the task.

**Comment by anselmbradford** [comment]
Err nevermind, if the packages aren't copied they will never be processed by https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L40. Instead how about turning off the verbose flag at https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L38 so there isn't output of the packages being copied to their same location. If so feedback at the command-line is needed, a `grunt.log.writeln(…)` message could be added in the `layout` loop.

**Comment by anselmbradford** [comment]
verbose can even be left off because the default is false.

**Comment by contolini** [comment]
![the bower task has been removed](https://cloud.githubusercontent.com/assets/1060248/8041954/d3692d26-0de9-11e5-960f-3a492d19e545.gif)
