### ISSUE TITLE
Is there any chance we could reuse things from cf-grunt-config?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/generator-cf#8]
It would be nice if the generator and the component shared [cf-grunt-config](https://github.com/cfpb/cf-grunt-config). This would make understanding the Grunt files easier as there wouldn't be two different workflows.

One potential issue I can think of is that projects will have different folder structures than components, so I'm not actually sure if this is possible but figured it was worth bringing up.

**Comment by anselmbradford** [comment]
Grunt removed in https://github.com/cfpb/generator-cf/pull/143
