### ISSUE TITLE
html5shiv should be added back to the generator

### ISSUE THREAD

**Issue by Scotchester** [cfpb/generator-cf#90]
It's a top-level thing that every HTML project needs, unless it's not supporting IE8. We should default to including it and let projects that don't support IE8 remove it.

**Comment by jimmynotjim** [comment]
When was it removed? I'm coming up empty outside of the printshiv.

**Comment by Scotchester** [comment]
https://github.com/contolini/generator-cf/commit/b0585ab2f00df0ce739c4bf6e2d1c736ad42d962

Part of PR #1, so I guess we can't really say it was "removed", but.

**Comment by contolini** [comment]
Oh sure -- blame @contolini -- I see how it is.
