### ISSUE TITLE
Add gulp option

### ISSUE THREAD

**Issue by contolini** [cfpb/generator-cf#91]
From @jimmynotjim in https://github.com/cfpb/front-end/issues/56#issuecomment-130360744

> If no one objects, I'll take this on. I've implemented the same Grunt/Gulp choice in the WP Evolved generator so it won't be difficult to do the same to the CF generator.

**Comment by jimmynotjim** [comment]
Almost done with this but I'm unsure if I should be including browserify by default since a few of our projects are now using it and it seems to be the best way to package scripts as needed. Any opinions?

**Comment by ascott1** [comment]
I would :+1: to browserify, but let's make that part of it's own PR.

**Comment by contolini** [comment]
Making it the default sounds good to me.

**Comment by Scotchester** [comment]
If it's made the default, let's please just make sure the instructions for adding one's own JS and adding new modules to the project are easy and clear.

**Comment by jimmynotjim** [comment]
Progress, just need to remove browserify (it is well embedded in our workflow at this point).

https://github.com/cfpb/generator-cf/compare/master...jimmynotjim:gulp-option?expand=1

**Comment by jimmynotjim** [comment]
Or, should we add Browserify to the Grunt workflow first, then continue down the Gulp path?

**Comment by jimmynotjim** [comment]
:musical_note: It finally happened, it finally happened, oh yes :musical_note: 

[Check the PR](https://github.com/cfpb/generator-cf/pull/103)

**Comment by jimmynotjim** [comment]
Released!!!
